// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SduCyberForm.Models;

namespace SduCyberForm.Migrations
{
    [DbContext(typeof(SCFDbContext))]
    [Migration("20210917125935_updateTableEventTypeModel")]
    partial class updateTableEventTypeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SduCyberForm.Models.CyberForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EventType")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysOutage")
                        .HasColumnType("bit");

                    b.Property<int>("TelNo")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CyberForm");
                });

            modelBuilder.Entity("SduCyberForm.Models.EventTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BilgiSizdirma")
                        .HasColumnType("bit");

                    b.Property<bool>("CihazKaybi")
                        .HasColumnType("bit");

                    b.Property<bool>("Ddos")
                        .HasColumnType("bit");

                    b.Property<bool>("Dolandiricilik")
                        .HasColumnType("bit");

                    b.Property<bool>("KimlikTaklidi")
                        .HasColumnType("bit");

                    b.Property<bool>("KisiselKotuKullanim")
                        .HasColumnType("bit");

                    b.Property<bool>("Malware")
                        .HasColumnType("bit");

                    b.Property<bool>("Oltalama")
                        .HasColumnType("bit");

                    b.Property<bool>("ParolaEleGec")
                        .HasColumnType("bit");

                    b.Property<bool>("PortTarama")
                        .HasColumnType("bit");

                    b.Property<bool>("SosyalMuh")
                        .HasColumnType("bit");

                    b.Property<bool>("Spam")
                        .HasColumnType("bit");

                    b.Property<bool>("VeriKaybi")
                        .HasColumnType("bit");

                    b.Property<bool>("VeriSaldiri")
                        .HasColumnType("bit");

                    b.Property<bool>("WebGuvenlik")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EventTypeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
